name: Lint code

on:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: Lint run
              uses: super-linter/super-linter@v6
              env:
                VALIDATE_ALL_CODEBASE: true
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                VALIDATE_CHECKOV: false
